### ISSUE TITLE
Password in token

### ISSUE THREAD

**Issue by partikule** [supermamon/node-restify-jwt-sample#2]
In case the user sends its password during registration, the register example just adds the password to the base64 token.
I know this is just an example and you don't pretend to provide an introduction to good security practices, but considering that a lot of newbies will just copypasta your code, this point should be at least explained.

`const token = jwt.sign(req.body, config.JWT_SECRET)`

should become something like : 

```
// Only put the username in the token, please read about JWT
let user = {name: req.body.name}
const token = jwt.sign(user, config.JWT_SECRET)
```

**Comment by supermamon** [comment]
Agreed. Fix coming up.
