### ISSUE TITLE
Postman can bypass protection and access admin-protected routes

### ISSUE THREAD

**Issue by ruanchaves** [supermamon/node-restify-jwt-sample#3]
I created a user with Postman and `role : test `.

Then I made a request with curl:  

![image](https://user-images.githubusercontent.com/14352388/53413423-b37c4480-39aa-11e9-96c8-cfb2e20aa331.png)

It works as expected: access denied.

Then I made exactly the same request again, with exactly the same token, but with Postman:  

![image](https://user-images.githubusercontent.com/14352388/53413447-c2fb8d80-39aa-11e9-920c-11793bba6e4d.png)

It bypasses protection and now I can access the admin-protected route with a test role.

**Comment by supermamon** [comment]
The issue is not with Postman but your `curl` command having a misspelled `Authorizatoon`. The `test` role is allowed in `/admin` because it's meant to be used for the test scripts.
